# ~/.local/share/chezmoi/.chezmoidata.yaml
packages:
  official:
    - yazi
    - bitwarden
    - bitwarden-cli
    - remmina
    - freerdp
    - wtype
    - expect
    - minikube
    - kubectl
  aur:
    - forticlient-vpn
    - anki
    - helium-browser-bin
